# typed: false
# frozen_string_literal: true

# This file is auto-generated by the dev-release workflow. DO NOT EDIT.
class GraithDev < Formula
  desc "Terminal session manager for AI coding agents (dev build)"
  homepage "https://github.com/d0ugal/graith"
  version "0.73.22-dev.1789274572"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/d0ugal/graith/releases/download/dev/graith-dev_0.73.22-dev.1789274572_darwin_arm64.tar.gz"
      sha256 "c3eb2f4438af5916dd5d8cc157be6c9c89fc380f464ba8e5944663030d184767"
    else
      odie "graith-dev supports only Apple Silicon on macOS"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/d0ugal/graith/releases/download/dev/graith-dev_0.73.22-dev.1789274572_linux_amd64.tar.gz"
      sha256 "9931d720595440fb90d13a32dacf7cc249af6e2bb685498c0bc58db97eddebc2"
    elsif Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/d0ugal/graith/releases/download/dev/graith-dev_0.73.22-dev.1789274572_linux_arm64.tar.gz"
      sha256 "6ac567a254d64ab63671805183cd0f4a71967396028686dd53d46f6dad028d36"
    else
      odie "graith-dev supports only Linux amd64/arm64"
    end
  end

  def install
    bin.install "gr-dev"
    if OS.mac?
      (libexec/"graith").install "GraithNotifier.app"
      if (buildpath/"Graith.app").directory?
        (libexec/"graith").install "Graith.app"
      end
    end
  end

  def caveats
    return unless (libexec/"graith/Graith.app").directory?

    <<~EOS
      To restart the graith-dev daemon after upgrading:
        gr-dev daemon restart

      Before uninstalling on macOS, remove its registered user service:
        gr-dev daemon service remove
    EOS
  end
end
