# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graith < Formula
  desc "Terminal session manager for AI coding agents"
  homepage "https://github.com/d0ugal/graith"
  version "0.41.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/d0ugal/graith/releases/download/v0.41.0/graith_0.41.0_darwin_amd64.tar.gz"
      sha256 "a329ee60084148e8158bf79a55ead361f4a4ec45eba8efbd9f9b516798f4ff71"

      define_method(:install) do
        bin.install "gr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/d0ugal/graith/releases/download/v0.41.0/graith_0.41.0_darwin_arm64.tar.gz"
      sha256 "c534256024188fdcc41437179ca7da380b6b3d895726e284c17c2b786d1cb9f9"

      define_method(:install) do
        bin.install "gr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/d0ugal/graith/releases/download/v0.41.0/graith_0.41.0_linux_amd64.tar.gz"
      sha256 "2054b448065c751f0ee02a2d379b25063fc0be989d03cf14801ac5e63ae4baed"
      define_method(:install) do
        bin.install "gr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/d0ugal/graith/releases/download/v0.41.0/graith_0.41.0_linux_arm64.tar.gz"
      sha256 "f49d44a18ca5d3f86cf2486e7814e8f6decc69b1a07094c842036bafaa938dea"
      define_method(:install) do
        bin.install "gr"
      end
    end
  end

  def caveats
    <<~EOS
      To restart the graith daemon after upgrading:
        gr daemon restart
    EOS
  end
end
