# typed: false
# frozen_string_literal: true

# This file is auto-generated by the dev-release workflow. DO NOT EDIT.
class GraithDev < Formula
  desc "Terminal session manager for AI coding agents (dev build)"
  homepage "https://github.com/d0ugal/graith"
  version "0.70.4-dev.1785089067"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/d0ugal/graith/releases/download/dev/graith-dev_darwin_arm64.tar.gz"
      sha256 "f05c7e0a6643609b8aed9778df457308078265258b05621a23b755a15e4d1783"
    else
      odie "graith-dev supports only Apple Silicon on macOS"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/d0ugal/graith/releases/download/dev/graith-dev_linux_amd64.tar.gz"
      sha256 "7640f574ae9cb2d88a2b18a86141d91c4972b55336602f1af9c74a5c67cb646d"
    elsif Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/d0ugal/graith/releases/download/dev/graith-dev_linux_arm64.tar.gz"
      sha256 "10952dfcc4a18d46ba2e0f6f2676f42d45b25e499252b6de969a45d826ade795"
    else
      odie "graith-dev supports only Linux amd64/arm64"
    end
  end

  def install
    bin.install "gr-dev"
    if OS.mac?
      (libexec/"graith").install "GraithNotifier.app"
      if (buildpath/"Graith.app").directory?
        (libexec/"graith").install "Graith.app"
      end
    end
  end

  def caveats
    return unless (libexec/"graith/Graith.app").directory?

    <<~EOS
      To restart the graith-dev daemon after upgrading:
        gr-dev daemon restart

      Before uninstalling on macOS, remove its registered user service:
        gr-dev daemon service remove
    EOS
  end
end
