# typed: false
# frozen_string_literal: true

# This file is auto-generated by the dev-release workflow. DO NOT EDIT.
class GraithDev < Formula
  desc "Terminal session manager for AI coding agents (dev build)"
  homepage "https://github.com/d0ugal/graith"
  version "0.70.3-dev.1784887333"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/d0ugal/graith/releases/download/dev/graith-dev_darwin_arm64.tar.gz"
      sha256 "9c7d000e8966da9b2b1855c7ee38d5e29cf3de98349e0449de92deadbd0ee098"
    else
      odie "graith-dev supports only Apple Silicon on macOS"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/d0ugal/graith/releases/download/dev/graith-dev_linux_amd64.tar.gz"
      sha256 "e3d7f5cb1f98da69060f8af30bf70ce56de34c0eacca21b80079c6712132c381"
    elsif Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/d0ugal/graith/releases/download/dev/graith-dev_linux_arm64.tar.gz"
      sha256 "a89c2815d0cbd7c2fd22a28b250f4104a89df819dd8c5d4502b6038f678c80e9"
    else
      odie "graith-dev supports only Linux amd64/arm64"
    end
  end

  def install
    bin.install "gr-dev"
    if OS.mac?
      (libexec/"graith").install "GraithNotifier.app"
      if (buildpath/"Graith.app").directory?
        (libexec/"graith").install "Graith.app"
      end
    end
  end

  def caveats
    return unless (libexec/"graith/Graith.app").directory?

    <<~EOS
      To restart the graith-dev daemon after upgrading:
        gr-dev daemon restart

      Before uninstalling on macOS, remove its registered user service:
        gr-dev daemon service remove
    EOS
  end
end
