# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graith < Formula
  desc "Terminal session manager for AI coding agents"
  homepage "https://github.com/d0ugal/graith"
  version "0.45.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/d0ugal/graith/releases/download/v0.45.0/graith_0.45.0_darwin_amd64.tar.gz"
      sha256 "e967aed8b3f5ff389494e3e6ccd58c55c37e91613d88ef90beef728b3440f2af"

      define_method(:install) do
        bin.install "gr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/d0ugal/graith/releases/download/v0.45.0/graith_0.45.0_darwin_arm64.tar.gz"
      sha256 "c5301ddbc5ca8d0d869ced8ad34c90a4d05993c8a4d62e4104539a040d37fdd1"

      define_method(:install) do
        bin.install "gr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/d0ugal/graith/releases/download/v0.45.0/graith_0.45.0_linux_amd64.tar.gz"
      sha256 "f7e9e53cf959d0f189a1f0b2d00940482628377adfa42cee13509651d9fc13da"
      define_method(:install) do
        bin.install "gr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/d0ugal/graith/releases/download/v0.45.0/graith_0.45.0_linux_arm64.tar.gz"
      sha256 "555b9938d2fcf16e8ac85c31a2e6670014f6c23e47d7809c74bd99ec558a40f2"
      define_method(:install) do
        bin.install "gr"
      end
    end
  end

  def caveats
    <<~EOS
      To restart the graith daemon after upgrading:
        gr daemon restart
    EOS
  end
end
