# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graith < Formula
  desc "Terminal session manager for AI coding agents"
  homepage "https://github.com/d0ugal/graith"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/d0ugal/graith/releases/download/v0.5.1/graith_0.5.1_darwin_amd64.tar.gz"
      sha256 "1cdd92c1c0f605e810ef146f50fcaa7601373a596f68e072dd4bb4f87cac8560"

      define_method(:install) do
        bin.install "gr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/d0ugal/graith/releases/download/v0.5.1/graith_0.5.1_darwin_arm64.tar.gz"
      sha256 "520974b670a88a4ce8637ef09dc769a37c6633799c00aedc17eecaf0281b34db"

      define_method(:install) do
        bin.install "gr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/d0ugal/graith/releases/download/v0.5.1/graith_0.5.1_linux_amd64.tar.gz"
      sha256 "f947e834c67acaf0dc29893300420d4274037341fc3afa8d5839828b62319f41"
      define_method(:install) do
        bin.install "gr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/d0ugal/graith/releases/download/v0.5.1/graith_0.5.1_linux_arm64.tar.gz"
      sha256 "6b4a72f4ae09cc3ddfc334cd262eb06e9a9ffb7049a0a7b040ef3312f6464142"
      define_method(:install) do
        bin.install "gr"
      end
    end
  end
end
